version: '3.1'
services:
  db:
    hostname: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
     - 3306:3306
  adminer:
    hostname: mysql
    image: adminer
    restart: always
    ports:
     - 8580:8080