spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task1?createDatabaseIfNotExist=true
    username: root
    password: pass
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  servlet:
    context-path: /api/v1

