spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:mysql://localhost:3306/task1
    username: root
    password: pass
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

#  spring.datasource.url=jdbc:mysql://localhost:3306/jwtappdemo?serverTimezone=UTC
#  spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#  spring.datasource.username=root
#  spring.datasource.password=root